// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package v1

// Product defines model for Product.
type Product struct {
	// Description Description of the product
	Description *string `json:"description,omitempty"`

	// Price Price of the product
	Price float64 `json:"price"`

	// ProductId ID of the product
	ProductId string `json:"product_id"`

	// ProductName Name of the product
	ProductName string `json:"product_name"`

	// StockQuantity Stock quantity
	StockQuantity int `json:"stock_quantity"`
}

// ProductSummary defines model for ProductSummary.
type ProductSummary struct {
	// Price Price of the product
	Price float64 `json:"price"`

	// ProductId ID of the product
	ProductId string `json:"product_id"`

	// ProductName Name of the product
	ProductName string `json:"product_name"`

	// StockQuantity Stock quantity
	StockQuantity int `json:"stock_quantity"`
}
