// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package v1

// ProductResponse defines model for ProductResponse.
type ProductResponse struct {
	// Description The description of the product
	Description *string `json:"description,omitempty"`

	// Name The name of the product
	Name string `json:"name"`

	// Price The price of the product
	Price float32 `json:"price"`

	// ProductID The unique identifier for the product
	ProductID string `json:"productID"`
}
