basePath: /
definitions:
  api.ErrorResponse:
    properties:
      message:
        type: string
      requestId:
        type: string
      statusCode:
        type: integer
    type: object
  types.BlockNumber:
    properties:
      chain_name:
        type: string
      number:
        type: string
    type: object
  types.CreateProduct:
    properties:
      address:
        type: string
      count:
        type: integer
      name:
        type: string
      price:
        type: number
    type: object
  types.Product:
    properties:
      count:
        type: integer
      name:
        type: string
      price:
        type: number
      productId:
        type: integer
    type: object
info:
  contact:
    email: feynmaz@gmail.com
    name: Nikolai Mazein
  description: Eggs shop on web3 technology
  title: Fresheggs API
  version: "1.0"
paths:
  /api/v1/product:
    post:
      parameters:
      - description: Create product
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/types.CreateProduct'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Product'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Create product
      tags:
      - post
  /api/v1/products:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.Product'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Get products
      tags:
      - get
  /eth/last_block:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.BlockNumber'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Get last eth block number
      tags:
      - get
swagger: "2.0"
