// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package v1

// Product defines model for Product.
type Product struct {
	Description   string  `json:"description"`
	Name          string  `json:"name"`
	Price         float64 `json:"price"`
	ProductId     string  `json:"product_id"`
	StockQuantity int     `json:"stock_quantity"`
}

// ProductCreate defines model for ProductCreate.
type ProductCreate struct {
	Description   string  `json:"description"`
	Name          string  `json:"name"`
	Price         float64 `json:"price"`
	StockQuantity int     `json:"stock_quantity"`
}

// ProductPatch defines model for ProductPatch.
type ProductPatch struct {
	Description   *string  `json:"description,omitempty"`
	Name          *string  `json:"name,omitempty"`
	Price         *float64 `json:"price,omitempty"`
	StockQuantity *int     `json:"stock_quantity,omitempty"`
}

// ProductSummary defines model for ProductSummary.
type ProductSummary struct {
	Name          string  `json:"name"`
	Price         float64 `json:"price"`
	StockQuantity int     `json:"stock_quantity"`
}

// PostProductJSONRequestBody defines body for PostProduct for application/json ContentType.
type PostProductJSONRequestBody = ProductCreate

// PatchProductProductIdJSONRequestBody defines body for PatchProductProductId for application/json ContentType.
type PatchProductProductIdJSONRequestBody = ProductPatch
