// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package v1

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Product defines model for Product.
type Product struct {
	Description   *string  `json:"description,omitempty"`
	Name          *string  `json:"name,omitempty"`
	Price         *float32 `json:"price,omitempty"`
	ProductId     *string  `json:"product_id,omitempty"`
	StockQuantity *int     `json:"stock_quantity,omitempty"`
}

// ProductCreate defines model for ProductCreate.
type ProductCreate struct {
	Description   *string  `json:"description,omitempty"`
	Name          *string  `json:"name,omitempty"`
	Price         *float32 `json:"price,omitempty"`
	StockQuantity *int     `json:"stock_quantity,omitempty"`
}

// ProductSummary defines model for ProductSummary.
type ProductSummary struct {
	Name          *string  `json:"name,omitempty"`
	Price         *float32 `json:"price,omitempty"`
	ProductId     *string  `json:"product_id,omitempty"`
	StockQuantity *int     `json:"stock_quantity,omitempty"`
}

// ProductBase defines model for _ProductBase.
type ProductBase struct {
	Name          *string  `json:"name,omitempty"`
	Price         *float32 `json:"price,omitempty"`
	StockQuantity *int     `json:"stock_quantity,omitempty"`
}

// PostProductJSONRequestBody defines body for PostProduct for application/json ContentType.
type PostProductJSONRequestBody = ProductCreate

// PatchProductProductIdJSONRequestBody defines body for PatchProductProductId for application/json ContentType.
type PatchProductProductIdJSONRequestBody = ProductCreate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create product
	// (POST /product)
	PostProduct(w http.ResponseWriter, r *http.Request)
	// Delete product by ID
	// (DELETE /product/{product_id})
	DeleteProductProductId(w http.ResponseWriter, r *http.Request, productId string)
	// Get product by ID
	// (GET /product/{product_id})
	GetProductProductId(w http.ResponseWriter, r *http.Request, productId string)
	// Update product by ID
	// (PATCH /product/{product_id})
	PatchProductProductId(w http.ResponseWriter, r *http.Request, productId string)
	// Get list of products
	// (GET /products)
	GetProducts(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Create product
// (POST /product)
func (_ Unimplemented) PostProduct(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete product by ID
// (DELETE /product/{product_id})
func (_ Unimplemented) DeleteProductProductId(w http.ResponseWriter, r *http.Request, productId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get product by ID
// (GET /product/{product_id})
func (_ Unimplemented) GetProductProductId(w http.ResponseWriter, r *http.Request, productId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update product by ID
// (PATCH /product/{product_id})
func (_ Unimplemented) PatchProductProductId(w http.ResponseWriter, r *http.Request, productId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get list of products
// (GET /products)
func (_ Unimplemented) GetProducts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostProduct operation middleware
func (siw *ServerInterfaceWrapper) PostProduct(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostProduct(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteProductProductId operation middleware
func (siw *ServerInterfaceWrapper) DeleteProductProductId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "product_id" -------------
	var productId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "product_id", runtime.ParamLocationPath, chi.URLParam(r, "product_id"), &productId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "product_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProductProductId(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetProductProductId operation middleware
func (siw *ServerInterfaceWrapper) GetProductProductId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "product_id" -------------
	var productId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "product_id", runtime.ParamLocationPath, chi.URLParam(r, "product_id"), &productId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "product_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProductProductId(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PatchProductProductId operation middleware
func (siw *ServerInterfaceWrapper) PatchProductProductId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "product_id" -------------
	var productId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "product_id", runtime.ParamLocationPath, chi.URLParam(r, "product_id"), &productId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "product_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchProductProductId(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetProducts operation middleware
func (siw *ServerInterfaceWrapper) GetProducts(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProducts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/product", wrapper.PostProduct)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/product/{product_id}", wrapper.DeleteProductProductId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/product/{product_id}", wrapper.GetProductProductId)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/product/{product_id}", wrapper.PatchProductProductId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/products", wrapper.GetProducts)
	})

	return r
}
