openapi: 3.0.0
info:
  title: Fresheggs
  description: Buy fresh eggs here
  version: 1.0.0

paths:
  /products:
    get:
      summary: Get list of products
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductSummary'
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /product:
    post:
      summary: Create product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCreate'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Bad request
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
  
  /product/{product_id}:
    parameters:
      - name: product_id
        in: path
        required: true
        schema:
          type: string

    get:
      summary: Get product by ID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Bad request
        '500':
          description: Internal server error

    delete:
      summary: Delete product by ID
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '500':
          description: Internal server error

    patch:
      summary: Update product by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCreate'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Bad request
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error

components:
  schemas:
    
    _ProductBase:
      type: object
      properties:
        name:
          type: string
        price:
          type: number
        stock_quantity:
          type: integer
  
    ProductSummary:
      allOf:
        - $ref: '#/components/schemas/_ProductBase'
        - type: object
          properties:
            product_id:
              type: string
              
    ProductCreate:
      allOf:
        - $ref: '#/components/schemas/_ProductBase'
        - type: object
          properties:
            description:
              type: string
              
    Product:
      allOf:
        - $ref: '#/components/schemas/ProductSummary'
        - type: object
          properties:
            description:
              type: string

